virtualsmartcard/src/vpicc/virtualsmartcard/SmartcardSAM.py
Apparently the function never worked which was not caught before because it's not used anywhere. I'll see if I can write a unit test or remove the function later.
=> Fix broken function SmartcardSAM.set_asym_cipher

ACardEmulator/README.md, README.md, TCardEmulator/README.md, ccid/README.md, npa/README.md, pcsc-relay/README.md, remote-reader/README.md, virtualsmartcard/README.md
GitHub changed the way Markdown headings are parsed, so this change fixes it.
See [bryant1410/readmesfix](https://github.com/bryant1410/readmesfix) for more information.
Tackles bryant1410/readmesfix#1
=> Fix broken headings in Markdown files

virtualsmartcard/src/vpicc/virtualsmartcard/SmartcardFilesystem.py
In FCP SFID tag bits 8 to 4 encode the short EF identifier.
=> Fix SFID parameter in FCP template

virtualsmartcard/src/vpicc/virtualsmartcard/SmartcardFilesystem.py
DF names shall be globally uniqe within a given card. Selecting by DF
name should be made on card level instead of current DF level.
A new list has been inroduced as a static attribute of MF in order to
track each named DF.
=> Fix selection by DF name

virtualsmartcard/src/vpicc/virtualsmartcard/SmartcardFilesystem.py, virtualsmartcard/src/vpicc/virtualsmartcard/utils.py
'Number of data bytes in the file' parameters should be represented on
two bytes in FCP.
=> Fix length of filesize parameter in FCP template

remote-reader/app/src/main/java/com/vsmartcard/remotesmartcardreader/app/MainActivity.java, remote-reader/app/src/main/java/com/vsmartcard/remotesmartcardreader/app/SettingsActivity.java, remote-reader/app/src/main/java/com/vsmartcard/remotesmartcardreader/app/screaders/NFCReader.java, remote-reader/app/src/main/res/values/strings.xml, remote-reader/app/src/main/res/xml/settings.xml
A quick modification to allow configuring an NFC response timeout for the remote-reader app.
I removed the `public static int TIMEOUT` field from `NFCReader`. I substituted the only other usage (in `MainActivity`, used for the default value of `EXTRA_READER_PRESENCE_CHECK_DELAY`) with its former value.
An increased timeout enables use of this app for Hungarian E-IDs (as discussed in issue #123 )
=> Configurable read timeout (remote-reader)

virtualsmartcard/src/vpicc/virtualsmartcard/cards/Relay.py
Hi,
We are using the virtual smart card reader to remotely authenticate using a smart card. We ran into problems because the APDU response was an unrecognised error. We found that when casting the relayed APDU response into a string to send to the VPICC, the string cast was not correct.
```
>>> # An example APDU response for a command CMD=[0x00, 0xCA, 0x01, 0xA0]
>>> res=[77, 121, 69, 73, 68, 4, 0, 0, 0, 0, 113, 105, 1, 86, 80, 152, 115, 149, 1, 14, 144, 0]
>>> 
>>> "".join([bytes(b) for b in res]) # The old code - incorrect
'7712169736840000113105186801521151491141440'
>>> 
>>> # Now the correct version
>>> map(chr, res) # Map the integer bytes first into bytes
['M', 'y', 'E', 'I', 'D', '\x04', '\x00', '\x00', '\x00', '\x00', 'q', 'i', '\x01', 'V', 'P', '\x98', 's', '\x95', '\x01', …
```
=> Fix cast of APDU res to byte array (aka string)

pcsc-relay/configure.ac, virtualsmartcard/MacOSX/Makefile.am, virtualsmartcard/configure.ac
Fixes compile errors in `pcsc-relay` on macOS 10.14 with Xcode 11.0 toolchain:
```
checking for SCardEstablishContext... configure: error: libpcsclite not found, use ./configure PCSC_LIBS=...
make[1]: *** [config.status] Error 1
make: *** [../aclocal.m4] Error 2
```
This is caused by using `--framework PCSC` instead of `-framework PCSC`.
Also fixes an issue with `make install` on `virtualsmartcard` on macOS 10.11+ (System Integrity Protection).  This fix was already in the macOS package installer, but wasn't in `configure.ac` so `make install` would fail.
I also _reversed_ those changes for `MacOSX/Makefile.am`, because then the paths are consistent regardless of whether it was built on macOS 10.11+ or not... but **this is still broken with macOS 10.14**.
This also fixes an error with …
=> (partially) fix macOS 10.14/Xcode 11.0 compile and install issues

appveyor.yml, virtualsmartcard/src/vpicc/virtualsmartcard/SEutils.py, virtualsmartcard/src/vpicc/virtualsmartcard/SmartcardSAM.py, virtualsmartcard/src/vpicc/virtualsmartcard/TLVutils.py, virtualsmartcard/src/vpicc/virtualsmartcard/VirtualSmartcard.py, virtualsmartcard/src/vpicc/virtualsmartcard/tests/SmartcardSAM_test.py
- Use pycryptodome instead of pycrypto
- Fixed some unit tests asserts
- fixed some instances that sending message to vpcd the msg is considered a string object instead of byte array
- make TLVutils.pack work in python 3
=> [vpicc] Python 3 updates and code fixing

virtualsmartcard/src/vpicc/Makefile.am, virtualsmartcard/src/vpicc/vicc.in, virtualsmartcard/src/vpicc/virtualsmartcard/VirtualSmartcard.py, virtualsmartcard/src/vpicc/virtualsmartcard/cards/Relay.py, virtualsmartcard/src/vpicc/virtualsmartcard/cards/RelayMiddleman.py
This PR extends the Relay class in such a way that it can be flexibly used as a Man-in-the-Middle.
It adds a new Command-Line Flag (--mitm) which takes a path to a Python File that contains a function `get_MitM()`, which, when called, produces an object with a `handleInPDU` and a `handleOutPDU` method. This object is then used by the Relay-VICC as a Man-in-the-Middel, meaning it passes any packets to these `handle`-Methods and relays the result of them (instead of the original packets).
For the MitM flag to work properly, the path which is given to it needs to be in Python's load path (eg PYTHONPATH).
The --mitm flag only applies when the Relay type is used. If the Relay is used without specifying a MitM-Module, the default `RelayMiddleman` is used, which does nothing at all.  The …
=> basic Man-in-the-Middle extension to the Relay-Card

remote-reader/app/build.gradle, remote-reader/app/src/main/java/com/example/android/common/logger/LogFragment.java, remote-reader/app/src/main/java/com/vsmartcard/remotesmartcardreader/app/AppCompatPreferenceActivity.java, remote-reader/app/src/main/java/com/vsmartcard/remotesmartcardreader/app/MainActivity.java, remote-reader/app/src/main/java/com/vsmartcard/remotesmartcardreader/app/MyLogFragment.java, remote-reader/app/src/main/java/com/vsmartcard/remotesmartcardreader/app/SettingsActivity.java, remote-reader/app/src/main/java/com/vsmartcard/remotesmartcardreader/app/VPCDWorker.java, remote-reader/app/src/main/res/layout/activity_main.xml, remote-reader/app/src/main/res/layout/content_main.xml, remote-reader/app/src/main/res/values/strings.xml, remote-reader/app/src/main/res/xml/settings.xml, remote-reader/build.gradle, remote-reader/gradle.properties, remote-reader/gradle/wrapper/gradle-wrapper.properties
Several improvements to the remote-reader Android app:
- Refactoring to new Android API (29), bump library versions, Gradle version, use AndroidX classes (removal of deprecated support lib)
- I've added more delay values to the preferences. In my scenario I have card operations that can take longer than 4 seconds (e.g., applet installation can take 6 seconds in my case).
- Listener / reversed mode added
The app now supports Listener mode as VICC supports.
- If enabled, ServerSocket start listening on a VPCD port
- Worker then waits on `accept()` for a client to connect (accept is timeouted to 1s and repeats with checking for cancellation)
- Once client connects, flow works as with connection mode
- When client disconnects, streams and client socket is closed and worker waits for another …
=> Improve remote-reader

ccid/doc/README.txt.in, docs/_sources/ccid/README.txt, docs/_sources/pcsc-relay/README.txt, docs/_sources/virtualsmartcard/README.txt, docs/ccid/README.html, docs/pcsc-relay/README.html, docs/virtualsmartcard/README.html, docs/virtualsmartcard/api/virtualsmartcard.cards.HandlerTest.html, pcsc-relay/doc/README.txt.in, virtualsmartcard/README.md, virtualsmartcard/doc/README.txt.in, virtualsmartcard/src/vpicc/virtualsmartcard/cards/HandlerTest.py
The web site moved from alioth.debian.org to apdu.fr
=> README.md: update PCSC-lite URL

virtualsmartcard/src/vpcd/vpcd.c
This should fix the appveyor build failure:
C:\projects\vsmartcard\virtualsmartcard\src\vpcd\vpcd.c(183): error C4700: uninitialized local variable 'rfds' used [C:\projects\vsmartcard\virtualsmartcard\win32\BixVReader\BixVReader.vcxproj]
=> vpcd: Initialize variable also on Windows

virtualsmartcard/src/vpicc/virtualsmartcard/CryptoUtils.py
hashlib is present in python since 2.5, however the previous versions only worked with PyCrypto installed.
=> Fallback to hashlib instead of deprecated libs

virtualsmartcard/src/vpcd/vpcd.c
Change socket fd checks against INVALID_SOCKET. Fix issue with allowing reconnects from client to a server.
Fixes https://github.com/frankmorgner/vsmartcard/issues/224
=> Client reconnect

virtualsmartcard/src/vpicc/virtualsmartcard/CryptoUtils.py
It is unused since commit 36970a26d72b4e2a63170b80c6af2b733ea14876
("Replace PBKDF2 class by python stdlib implementation").
Fixes #218
=> Drop unused SHA1 import

virtualsmartcard/src/vpicc/virtualsmartcard/CryptoUtils.py
As described in #223 and in the commit message of the commit in this PR in more detail, the changed `hmac` import from commit 82c0c4fdd2d99150ed11c188fbc0586512b13edb (PR #215) does not appear to work and also does not match with what the example in the [official Python 3.10 documentation](https://docs.python.org/3/library/hashlib.html) uses, so this reverts the import to the working version again.
@Gu1nness: Anything I might possibly be missing here?
=> Correct hmac import from Python stdlib

.appveyor.yml, docs/_sources/virtualsmartcard/README.txt, docs/virtualsmartcard/README.html, virtualsmartcard/doc/README.txt.in, virtualsmartcard/src/vpicc/virtualsmartcard/CryptoUtils.py, virtualsmartcard/src/vpicc/virtualsmartcard/SEutils.py, virtualsmartcard/src/vpicc/virtualsmartcard/cards/cryptoflex.py
As suggested in https://github.com/frankmorgner/vsmartcard/issues/223#issuecomment-1234280271, this ports from the deprecated and unmaintained PyCrypto to the recommended and maintained PyCryptodome fork, s. discussion there and commit messages for more details.
Further comments:
1) The (only) use case I explicitly tested was retrieving my personal data using the German passport (nPA) with a virtual smartcard reader (Smart Card Reader Android app running under LineageOS, AusweisApp2 and vicc from this repo running under Debian testing, using Python 3.10.7). The [PyCryptodome doc](https://www.pycryptodome.org/src/introduction) says that Python 2.7 is also supported, but I didn't explicitly test that.
2) From how I understand it, generating/updating the docs should be possible by running …
=> Port from PyCrypto to PyCryptodome

remote-reader/app/src/main/java/com/vsmartcard/remotesmartcardreader/app/VPCDWorker.java, virtualsmartcard/src/vpcd/vpcd.c
when using remote-reader + vpcd, the request is sent by doing 2 `sendall` operations on the socket (one for the length, another for the data). this splits the request into 2 TCP segments, meaning Nagle's algorithm kicks in and holds the second segment until an ACK for the first is received. this introduces an unnecessary RTT.
remote-reader also does this on their end, which introduces another RTT. these RTTs can end up representing most of the time the user spends waiting (with Android they're usually on the order of hundreds of milliseconds).
in conclusion, this makes overall operation ~3x faster. for example, in my case `pkcs15-tool -c` drops from 6.3 seconds to about 2 seconds.
=> avoid unnecessary RTTs for communication

ccid/src/scutil.c
Terminate the log message with a line break, so that subsequent
messages aren't concatenated with it.
=> Missing newline in CCID error

.github/workflows/ci.yml, remote-reader/app/build.gradle, remote-reader/build.gradle, remote-reader/gradle/wrapper/gradle-wrapper.properties
I updated some stuff to correctly compile Android application. I tested Gradle compilation process on Manjaro and Ubuntu 20.04 (GitHub runner, click [here](https://github.com/user-attachments/files/16790662/job-logs.txt) to download the `job-log` or [here](https://github.com/miticollo/vsmartcard/actions/runs/10607011107/job/29398735847) to see the job). I installed and tested the (debuggable) app on Samsung Galaxy S10+ with Android 12.
Some update details are added into commit body.
=> Remote Smart Card Reader: Bump outdated

remote-reader/app/src/main/java/com/vsmartcard/remotesmartcardreader/app/screaders/NFCReader.java
Hi, thanks for the project! It has been very useful so far :)
For Type B cards, the Android app is currently calling [IsoDep#getHiLayerResponse()](https://developer.android.com/reference/android/nfc/tech/IsoDep#getHiLayerResponse()) to get the data to use as historical bytes in the generated wrapped ATR. According to the documentation, this method returns "a subset of the data in the ATTRIB response".
This is not compliant to the PC/SC spec; in the section defining what the wrapped ATR should be, it reads:
For 14443 Type B smartcards, the historical data should be constructed from two fields of the ATQB (the application data and the protocol info) and a nibble from ATTRIB. This pull request implements this correctly by grabbing the necessary info from `NfcB`.
=> [remote-reader] Fix ATR for 14443 Type B cards
